[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remapping =['@openzeppelin/contracts=contracts/openzeppelin/contracts']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config